version: "3.9"
services:
  api:
    build: { context: ./, dockerfile: backend/Dockerfile.api }
    container_name: sima-cloud-api
    ports: ["8080:8080"]
    env_file: [backend/.env]
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost:8080/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks: [sima_net]

  llm:
    build: { context: ./, dockerfile: llm/Dockerfile.llm }
    container_name: sima-local-llm
    ports: ["7070:7070"]
    networks: [sima_net]

  cloud-relay:
    build: { context: ./, dockerfile: cloud-relay/Dockerfile.relay }
    container_name: sima-cloud-relay
    environment: # Provide provider URLs/keys at runtime to enable
      - OPENAI_URL=
      - OPENAI_KEY=
    ports: ["9090:9090"]
    networks: [sima_net]

  web:
    build: { context: ./, dockerfile: frontend/Dockerfile.web }
    container_name: sima-cloud-web
    environment: [ "NEXT_PUBLIC_API_BASE=http://api:8080" ]
    depends_on: { api: { condition: service_healthy } }
    ports: ["3000:3000"]
    networks: [sima_net]

networks:
  sima_net: {}
