# Render Blueprint for Full Stack Deployment
services:
  # PostgreSQL Database
  - type: pserv
    name: sima-ai-db
    plan: starter
    
  # Backend API Service
  - type: web
    name: sima-ai-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sima-ai-db
          property: connectionString
      - key: CORS_ORIGIN
        value: "*"
    
  # Frontend Web Service  
  - type: web
    name: sima-ai-frontend
    env: node
    plan: starter
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://sima-ai-backend.onrender.com