global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'api'
    static_configs:
    - targets: ['api:8080']
  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
    - targets: ['api:8080']  # استبدلها إذا كان لديك exporter منفصل
